### ISSUE TITLE
Versionsnummer Startbildschirm

### ISSUE THREAD

**Issue by hannespreishuber** [ppedvAG/pocgen#11]
Die Frage ist habe ich die aktuelleste Version
evtl Autoupdate?

**Comment by ppedvMZ1** [comment]
Die aktuelle Versionsnummer findet man sehr schnell mit einem Klick auf die Schaltfläche "About" oben Rechts im Menü heraus.
![image](https://user-images.githubusercontent.com/26328672/64317560-6233ba00-cfb8-11e9-844f-d8a87046697c.png)

Ein automatischer Abgleich der Versionen (und eventuelles Autoupdate-Feature) wären tatsächlich praktische Features für künftige Versionen
