### ISSUE TITLE
Sortierung Folien

### ISSUE THREAD

**Issue by hannespreishuber** [ppedvAG/pocgen#12]
gibts ein Konzept? 
am einfachsten ist 00... bis 16...

**Comment by ppedvMZ1** [comment]
Aktuell wäre eine fortlaufende Ordner- und Foliennummerierung am sinnvollsten. Zurzeit ist geplant, dass die Nummerierung und die Reihenfolge der Folien künftig auch innerhalb von pocgen geändert werden kann.

Ein Namensschema für die Folien wäre aber auch an anderen Orten (z.B. Teams) wünschenswert.

**Comment by Rauchendraser** [comment]
ich würde für folgendes Format plädieren..  :
001_Modulthema.pptx
Dann muss man in pcogen nicht umsortieren, sofern pocgen aplhanumerisch aufsteigend vorsortiert

**Comment by ppedvMZ1** [comment]
> ich würde für folgendes Format plädieren.. : dd_Thema.filetype
> 01_Modulthema.pptx (führende 0!)
> 
> Dann muss man in pcogen nicht umsortieren, sofern pocgen aplhanumerisch aufsteigend vorsortiert

Die Diskussion über das ge/erwünschte Folienformat sollten wir im Trainerteam in Teams führen statt in diesem Issuetracker. Die Sortierungsmechanismen in pocgen werden daraufhin auf das dort beschlossene Ergebnis angepasst.

**Comment by Rauchendraser** [comment]
> Die Diskussion über das ge/erwünschte Folienformat sollten wir im Trainerteam in Teams führen statt in diesem Issuetracker. Die Sortierungsmechanismen in pocgen werden daraufhin auf das dort beschlossene Ergebnis angepasst.

wieso in Teams.. welchen Vorteil hätte man?

**Comment by hannespreishuber** [comment]
sortiert nach name
pptx wie folgt benennen 00blazortraining 01 02 ....
