### ISSUE TITLE
Leichter Layout Fehler

### ISSUE THREAD

**Issue by hannespreishuber** [ppedvAG/pocgen#13]
![image](https://user-images.githubusercontent.com/3587156/64092457-2d73f880-cd55-11e9-9ebb-88ec379fcf4a.png)

**Comment by ppedvMZ1** [comment]
Die Reiter "Aktionen" und "Vorschau" können mithilfe der blauen Balken je nach Bedarf vergrößert oder verkleinert werden. Dies ermöglicht beispielsweise, dass man die Vorschau im Vollbildmodus stark vergrößern kann.

Diese Beschreibung werde ich auch gleich mal in die Info einbauen :)
