### ISSUE TITLE
Erstellung von Slides  in pdf 

### ISSUE THREAD

**Issue by Rauchendraser** [ppedvAG/pocgen#14]
Dauert ewig, selbst nach 5 min sind 50 Folien noch nicht konvertiert.

**Comment by hannespreishuber** [comment]
grad mit 100 Folien probiert 2-3 sekunden...da Pocgen keine Version anzeigt... ist das die neue bunte...
![pocgen](https://user-images.githubusercontent.com/3587156/80370277-18257e80-8890-11ea-96de-07ff3ae27377.PNG)

**Comment by AndreRRR** [comment]
Falls das Problem noch besteht, bitte ein neues Issue erstellen.
