### ISSUE TITLE
MSI Installer wird blockiert

### ISSUE THREAD

**Issue by hannespreishuber** [ppedvAG/pocgen#17]
Download bricht ab bzw installation ist nicht möglich

**Comment by AndreRRR** [comment]
Bei Edge in der Downloadliste auf die drei Punkte neben der Datei klicken und 'Beibehalten' auswählen, das sollte das Problem beheben.

![image](https://user-images.githubusercontent.com/26326677/117133712-e6999a00-ada4-11eb-8141-f38523611427.png)

**Comment by ppedvStefanO** [comment]
Sowohl Download als auch Installation wird von Defender / Smart Screen blockiert aufgrund fehlender Signatur.

**Comment by AndreRRR** [comment]
Das Problem wird evtl. durch #21 gelöst werden.
