### ISSUE TITLE
Preview Optionen 

### ISSUE THREAD

**Issue by hannespreishuber** [ppedvAG/pocgen#2]
unklar was die Optionen bewirken

<img width="300" alt="ordner2" src="https://user-images.githubusercontent.com/3587156/49449201-afd98700-f7da-11e8-83b7-f0db99f28816.PNG">

**Comment by ppedvMZ1** [comment]
Version 1.2 nutzt nun gewisse Standardeinstellungen, das Optionssystem wird aktuell überarbeitet und ist in 1.2 nicht mehr verfügbar
