### ISSUE TITLE
PocGen generiert kein Word Dokument

### ISSUE THREAD

**Issue by Rauchendraser** [ppedvAG/pocgen#9]
PocGen generiert seit gestern keine Worddokumente mehr. Leider keine Versionsnummer zu finden.

**Comment by ppedvMZ1** [comment]
Tritt der Fehler auch in der neusten Version (1.3) auf ? Wenn ja, bitte eine genaue Fehlerbeschreibung mitgeben, damit man der Sache auf den Grund gehen kann. Idealerweise mit der Windows-Schrittaufzeichnung.

**Comment by Rauchendraser** [comment]
PocGen generiert wieder.... Vermute, dass es aufgrund der viele Folien  sehr lange gedauert hatte. Fortschritsbalken?

**Comment by ppedvMZ1** [comment]
Siehe #7
